pedestrian/urls.py
from django.conf.urls import patterns, include, url
from places.models import Place

from django.contrib import admin
admin.autodiscover()

from places.views import *

urlpatterns = patterns('',
    # Examples:
    url(r'^$', PlacesList.as_view(template_name='index.html'), name='home'),
    url(r'^maps/$', MapView.as_view(), name='maps'),
    url(r'^places/$', PlacesList.as_view(), name='places'),
    url(r'^p/', include('django.contrib.flatpages.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^post/', include('posts.urls', namespace='posts')),
)

posts/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from .views import *
from .models import *

urlpatterns = patterns('',
        url(r'^(?P<slug>[\w-]+)/$', PostDetailView.as_view(), name='post'),
        #url(r'^edit/new/$', TemplateView.as_view(template_name="posts/post_new.html"), name="new_post"),
        url(r'^$', ListView.as_view(
            model=Post, 
            queryset=Post.objects.all(), 
            paginate_by=10,
            context_object_name='posts'), name='all-posts')
)

places/models.py
from django.db import models
from django_countries.fields import CountryField
# Create your models here.

class Place(models.Model):
    lat = models.FloatField()
    lng = models.FloatField()
    name = models.CharField(max_length=200)
    country = CountryField()
    wikilink = models.URLField()

    def __unicode__(self):
        return unicode(self.name)

posts/models.py
from django.db import models

from places.models import Place
# Create your models here.

class Affiliate(models.Model):
    title = models.CharField(max_length=40)
    link = models.TextField()

    def __unicode__(self):
        return unicode(self.title)

class Post(models.Model):
    title = models.CharField(max_length=200)
    title_pic = models.ImageField(upload_to='%Y/%m/title')
    thumbnail_pic = models.ImageField(upload_to='%Y/%m/thumbnails/')
    place = models.ForeignKey(Place)
    content = models.TextField()
    promotions = models.ManyToManyField(Affiliate, null=True)
    created = models.DateTimeField(auto_now=True)
    slug = models.SlugField()
    published = models.BooleanField(default = False)
    
    def __unicode__(self):
        return unicode(self.title)

class Image(models.Model):
    place = models.ForeignKey(Place, null=True)
    post = models.ForeignKey(Post, null = True, related_name="images")
    title = models.CharField(max_length=200)
    image = models.ImageField()

places/views.py
from django.shortcuts import render
from django.views.generic.list import ListView

from .models import *
from posts.models import *
# Create your views here.

class PlacesList(ListView):
    queryset = Place.objects.all()
    context_object_name = 'places'
    
    def get_context_data(self, *args, **kwargs):
        p = Post.objects.all().order_by('-created')[:5]
        context = super(PlacesList, self).get_context_data(*args, **kwargs)
        context.update({'posts': p})
        return context

class MapView(PlacesList):
    template_name = 'places/maps.html'

posts/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from .models import *
from places.models import * 

# Create your views here.

class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'

    def get_context_data(self, *args, **kwargs):
        context = super(self.__class__, self).get_context_data(*args, **kwargs)
        return context

class PostList(ListView):
    model = Post
    context_object_name = 'post'

    def get_context_data(self, *args, **kwargs):
        context = super(PostList, self).get_context_data(*args, **kwargs)
        context['countries'] = [

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %} {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <!-- <link href={% static "css/bootstrap.min.css" %} rel="stylesheet"> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href={% static "css/common.css" %}>

    <!-- Custom styles for this template -->
    <!-- <link href={% static "css/grid.css" %} rel="stylesheet"> -->

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block extrahead %}{% endblock %}
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">the pedestrian</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><a href="#">Home <span class="sr-only">(current)</span></a></li>
              <li><a href="#">About Pedestrian</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> j<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                  <li class="divider"></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">en <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">fr</a></li>
                </ul>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

      {% block content %} {% endblock %}
    </div> <!-- /container -->
    
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

{% endblock %}

templates/places/maps.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="posts">
  <h1 class="content-subhead">Maps</h1>
  <div id='map' style="width: 100%; height: 500px"></div>
</div>
{% endblock %}

{% block extrascript %}
<script src={% static 'js/markerclusterer.js' %}></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDoJaqwtRSj3bRfiKrI81w-zeKBWu3hDiE&sensor=false" type="text/javascript"></script>
<script type="text/javascript">
var places = [
    {% for p in places %}
      {lat: {{p.lat}}, lng: {{p.lng}}, name: '{{p.name}}', wiki: '{{p.wikilink}}', desc: '{{p.description}}'},
    {% endfor %}
]
var map;
var markers = [];
function addMarker(d){
    var marker = new google.maps.Marker({
	position: new google.maps.LatLng(d.lat, d.lng),
	title: d.name
    });
    marker.setMap(map);
    google.maps.event.addListener(marker, 'click', function(){
	new google.maps.InfoWindow({
	    content: '<h4>' + d.name + '</h4><p>'+d.desc+'</p><p><a target="_blank" href="'+d.wiki+'">'+d.wiki+'</a></p>'
	}).open(map, marker);
    });
}

function InitMap(){
    var mapoptions = {
	zoom: 4,
	center: new google.maps.LatLng(23.6, 79.1)
    }
    map = new google.maps.Map(document.getElementById('map'),mapoptions);
    for (place in places){
	addMarker(places[place]);
    }
}
google.maps.event.addDomListener(window, 'load', InitMap);
</script>
{% endblock %}

templates/places/place_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<ul>
  {% for post in posts %}
  <li><a href={% url 'posts:post' slug=post.slug %}>{{ post.title }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

templates/posts/index.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Post - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/blog-post.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Blog Post -->

                <!-- Title -->
                <h1>Blog Post Title</h1>

                <!-- Author -->
                <p class="lead">
                    by <a href="#">Start Bootstrap</a>
                </p>

                <hr>

                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>

                <hr>

                <!-- Preview Image -->
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">

                <hr>

                <!-- Post Content -->
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

                <hr>

                <!-- Blog Comments -->

                <!-- Comments Form -->
                <div class="well">
                    <h4>Leave a Comment:</h4>
                    <form role="form">
                        <div class="form-group">
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

                <hr>

                <!-- Posted Comments -->

                <!-- Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </div>

                <!-- Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                        <!-- Nested Comment -->
                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object" src="http://placehold.it/64x64" alt="">
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading">Nested Start Bootstrap
                                    <small>August 25, 2014 at 9:30 PM</small>
                                </h4>
                                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                            </div>
                        </div>
                        <!-- End Nested Comment -->
                    </div>
                </div>

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

templates/posts/post_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extrahead %}
<link href={% static "css/blog-post.css" %} rel="stylesheet">
{% endblock %}

{% block title %} {{post.title}} {% endblock %}

{% block content %}

<div class="row post-top">
  <!-- Blog Post Content Column -->
  <div class="col-lg-8">
    <!-- Blog Post -->
    <!-- Title -->
    <div class="page-header">
      <h2>{{ post.title }}</h2> <small>{{post.created}}</small>
    </div>

    <!-- Preview Image -->
    <img class="img-responsive" src="/static/images/{{post.title_pic}}" alt="">
    <hr>
    <!-- Post Content -->
    <p>{{ post.content | safe }}</p>
  </div>
  <!-- Blog Sidebar Widgets Column -->
  <div class="col-md-4">
    <!-- Blog Search Well -->
    <div class="well">
      <h4>Search</h4>
      <div class="input-group">
        <input type="text" class="form-control">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div>
      <!-- /.input-group -->
    </div>
    <!-- Blog Categories Well -->
    <div class="well">
      <h4>Blog Categories</h4>
      <div class="row">
        <div class="col-lg-6">
          <ul class="list-unstyled">
            <li><a href="#">{{post.place.name}}</a>
            </li>
            <li><a href="{{post.place.link}}">Wiki</a></li>
          </ul>
        </div>
        <div class="col-lg-6">
          <ul class="list-unstyled">
            <li><a href="#">{{post.place.country.name}}</a>
            </li>
          </ul>
        </div>
      </div>
      <!-- /.row -->
    </div>
    <!-- Side Widget Well -->
    <div class="well">
      <h4>Buy these now !</h4>
      {% for i in post.promotions.all %}
      <div class="row">
        <div class="col-md-1"> {{ i.link | safe }}</div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<!-- /.row -->
<hr>
<!-- Footer -->
<footer>
  <div class="row">
    <div class="col-lg-12">
      <p>Copyright &copy; http://thepedestrian.in 2015</p>
    </div>
  </div>
  <!-- /.row -->
</footer>
</div>
<!-- /.container -->

{% endblock %}

templates/posts/post_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="pure-u-1-2"></div>
<div class="pure-u-1">
  {% for post in posts %}
  <li><a href={% url 'posts:post' slug=post.slug %}>{{ post.title }}</a></li>
  {% endfor %}
</div>
{% endblock %}

templates/posts/post_new.html
{% load staticfiles %}

{% block extrahead %}
   <link rel="stylesheet" href={% static "quill/themes/quill.snow.css" %} />
{% endblock %}

{% block content %}
   <div class="pure-u-21-24">
     <input id="name" type="text" placeholder="Title" class="pure-input-1">
       <div id="toolbar" class="toolbar sc-toolbar-container">
	 <div class="quill-wrapper">
	   <div id="toolbar-toolbar" class="toolbar sc-toolbar-container">
	     <span class="sc-format-group">
	       <select class="sc-font">	 	
		 <option value="sans-serif" selected="">Sans Serif</option>
		 <option value="serif">Serif</option>
		 <option value="monospace">Monospace</option>
	       </select>
	     </span> 
	     <span class="sc-format-group">
	       <select class="sc-size">
		 <option value="small">Small</option>
		 <option value="normal" selected>Normal</option>
		 <option value="large">Large</option>
		 <option value="huge">Huge</option>
	       </select>
	     </span>
	     <span class="sc-format-group">
	       <span title="Bold" class="sc-format-button sc-bold"></span>
	       <span class="sc-format-separator"></span>
	       <span title="Italic" class="sc-format-button sc-italic"></span>
	       <span class="sc-format-separator"></span>
	       <span title="Underline" class="sc-format-button sc-underline"></span>
	       <span class="sc-format-separator"></span>
	       <span title="Strikethrough" class="sc-format-button sc-strike"></span>
	     </span>
	     <!-- image and link --> 
	     <span class="sc-format-group">
	       <span class="sc-format-button sc-link" title="Link"></span>
	       <span class="sc-format-separator"></span>
	       <span class="sc-format-button sc-image" title="Image"></span>
	     </span>
	   </div>
	   
	   <div id="editor" class="editor">
	     
	   </div>
	   <button class="pure-button pure-button-primary">Save</button>
</div>
{% endblock %}

{% block extrascript %}
<script src={% static "quill/quill.min.js" %}></script>
<script>
var editor = new Quill("#editor", {
    theme: 'snow', 
    modules: {
	'toolbar': { container: '#toolbar'},
	'image-tooltip': true,
	'link-tooltip': true
    }
});
</script>
{% endblock %}